### ISSUE TITLE
Script loaded over http

### ISSUE THREAD

**Issue by dazerdude** [jbiatek/BSGRulebook#10]
The site redirects to load over https, and then doesn't load jquery over a secure connection. As a result chrome disallows the javascript from loading, and the dynamic content breaks.

**Comment by jbiatek** [comment]
Hmm. I'm not seeing a redirect, but there's no reason jQuery can't be loaded over HTTPS either way. I'll see if I can fix this on mobile.

**Comment by jbiatek** [comment]
That should do it. Literally a 1 character fix. Yay computers.
