### ISSUE TITLE
Compiled, single-file download, for offline use?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jbiatek/BSGRulebook#11]
Can this be a thing?

**Comment by jbiatek** [comment]
I think using your web browser's "save complete web page" feature should work to create an offline version. All the dynamic stuff is contained within the page, and it doesn't defer any resources or anything like that. I don't know a good way to do this on mobile though. People have asked for an app but I don't really want to get in to that.

**Comment by NullVoxPopuli** [comment]
maybe a zip download of the "save complete web page" for mobile?
