### ISSUE TITLE
Set Rule State from URL to share configurations

### ISSUE THREAD

**Issue by trasa** [jbiatek/BSGRulebook#6]
Hi - First, excellent work with this. As someone who plays BSG often but not enough to have memorized all the rules across all the configurations that I end up playing in, this will be very helpful!

A feature that would be 'nice to have' is to be able to share with other players a configuration - where I go in, check rule checkboxes, "for tonight's game we're using this feature, but not that one," and then be able to email this URL to the other players so they'll also be looking at the same set of rules.

**Comment by jbiatek** [comment]
That's a good idea, I've thought of that too. It didn't occur to me to check if JavaScript can handle URL parameters, but it looks like it can, although not natively. If I have time it probably won't be too hard to add. There's already some code for saving and loading settings from browser local storage, so something similar would probably work for shareable URLs too.

**Comment by jbiatek** [comment]
Merged, thanks!
